// --   `idAddress` int(11) NOT NULL AUTO_INCREMENT,
// --   `number` varchar(50) DEFAULT NULL,
// --   `lineA` varchar(50) DEFAULT NULL,
// --   `lineB` varchar(50) DEFAULT NULL,
// --   `zipCode` varchar(50) DEFAULT NULL,
// --   `city` varchar(50) DEFAULT NULL,
// --   `createdAt` datetime DEFAULT NULL,
// --   `updatedAt` datetime DEFAULT NULL,
// --   `deletedAt` datetime DEFAULT NULL,

